server:
  port: 9000
dubbo:
  registry:
    register: true
    protocol: zookeeper
    address: ${zk_address:127.0.0.1:2181}
  application:
    name: ${APP_NAME:dubbo-bug-server}
    serialize-check-status: WARN
    check-serializable: false
    qos-enable: false
  consumer:
    timeout: 10000
    retries: 0
    check: false
  protocol:
    name: dubbo
    port: -1
    threadname: dubbo-thread
    threadpool: eager
    dispatcher: message
    threads: 200
    corethreads: 50
    queues: 2000
  service:
    shutdown:
      wait: 60